### ISSUE TITLE
[Bug]: Issues on installation Pybamm

### ISSUE THREAD

**Issue by danmarc89409** [pybamm-team/PyBaMM#2485]
### PyBaMM Version

 pybamm-22.10.post1.tar.gz

### Python Version

3.9.0

### Describe the bug

Hi everyone, 

Im trying to install pybamm on windows using command prompt. When launch pip install pybamm on virtual env. Below are the output. 

Thanks in advance!

### Steps to Reproduce

this is the code i wrote:
C:\Users\DANIELE\Desktop\pybamm>env\Scripts\activate.bat

(env) C:\Users\DANIELE\Desktop\pybamm>pip install pybamm

### Relevant log output

```shell
(env) C:\Users\DANIELE\Desktop\pybamm>pip install pybamm
Collecting pybamm
  Using cached pybamm-22.10.post1.tar.gz (904 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.16
  Using cached numpy-1.23.5-cp39-cp39-win32.whl (12.2 MB)
Collecting scipy>=1.3
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      + meson setup --prefix=C:\Users\DANIELE\Desktop\Python 39 C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6 C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6\.mesonpy-t6ws9xcz\build --native-file=C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      The Meson build system
      Version: 0.64.1
      Source dir: C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6
      Build dir: C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6\.mesonpy-t6ws9xcz\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `cl /?` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `cc --version` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `gcc --version` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `clang --version` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `clang-cl /?` gave "[WinError 2] Impossibile trovare il file specificato"
      Running `pgcc --version` gave "[WinError 2] Impossibile trovare il file specificato"

      A full log can be found at C:\Users\DANIELE\AppData\Local\Temp\pip-install-4_v_te0o\scipy_842a01b8b5e14259b183a32c7f31dac6\.mesonpy-t6ws9xcz\build\meson-logs\meson-log.txt
      Traceback (most recent call last):
        File "C:\Users\DANIELE\Desktop\pybamm\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\DANIELE\Desktop\pybamm\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\DANIELE\Desktop\pybamm\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\DANIELE\Desktop\pybamm\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "C:\Users\DANIELE\Desktop\Python 39\lib\contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\DANIELE\Desktop\Python 39\lib\contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "C:\Users\DANIELE\AppData\Local\Temp\pip-build-env-5bz26h8o\overlay\Lib\site-packages\mesonpy\__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "C:\Users\DANIELE\Desktop\Python 39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=C:\\Users\\DANIELE\\Desktop\\Python 39', 'C:\\Users\\DANIELE\\AppData\\Local\\Temp\\pip-install-4_v_te0o\\scipy_842a01b8b5e14259b183a32c7f31dac6', 'C:\\Users\\DANIELE\\AppData\\Local\\Temp\\pip-install-4_v_te0o\\scipy_842a01b8b5e14259b183a32c7f31dac6\\.mesonpy-t6ws9xcz\\build', '--native-file=C:\\Users\\DANIELE\\AppData\\Local\\Temp\\pip-install-4_v_te0o\\scipy_842a01b8b5e14259b183a32c7f31dac6\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by danmarc89409** [comment]
Thank you, it worked fine
