### ISSUE TITLE
[Bug]:  Issue with US06 experiment conditions

### ISSUE THREAD

**Issue by skywo1f** [pybamm-team/PyBaMM#2698]
### PyBaMM Version

22.11.1

### Python Version

3.9

### Describe the bug

Traceback (most recent call last):
  File "/home/iviti/batterySims/nmc_simple.py", line 22, in <module>
    exp = pybamm.Experiment(
  File "/home/iviti/anaconda3/lib/python3.9/site-packages/pybamm/experiments/experiment.py", line 130, in __init__
    self.operating_conditions = [
  File "/home/iviti/anaconda3/lib/python3.9/site-packages/pybamm/experiments/experiment.py", line 131, in <listcomp>
    self.read_string(cond, drive_cycles) for cond in operating_conditions
  File "/home/iviti/anaconda3/lib/python3.9/site-packages/pybamm/experiments/experiment.py", line 200, in read_string
    dc_data = drive_cycles[cond_list[1]]
KeyError: 'US06'

### Steps to Reproduce

exp = pybamm.Experiment(
    [
             "Run US06 (V)",
            "Rest for 5 minutes",

    ]
)

**Comment by skywo1f** [comment]
looking at the experiment_drive_cycle.py example it looks like I missed:

drive_cycle_current = pd.read_csv(
    "pybamm/input/drive_cycles/US06.csv", comment="#", header=None
).to_numpy()
