### ISSUE TITLE
[Bug]: mxstep steps taken before reaching tout with customized piecewise LFP OCP function

### ISSUE THREAD

**Issue by yaomz16** [pybamm-team/PyBaMM#2765]
### PyBaMM Version

23.1

### Python Version

3.9.5

### Describe the bug

I was using Prada2013 dataset & my customized LFP OCV function, and I encounter "At t = 0.00500431, , mxstep steps taken before reaching tout." warning & simulation breaks down when the simulated time is long:
```
param = model.default_parameter_values
timescale = param.evaluate(model.timescale)
t_end = 0.15*timescale 
t_eval = np.linspace(0, t_end, 1500)
```
However, if I set 
```
t_end = 0.10*timescale 
t_eval = np.linspace(0, t_end, 1000)
```
the simulation goes well and I get the simulated result. 

### Steps to Reproduce

```
parameter_values = pybamm.ParameterValues("Prada2013")
parameter_values["Positive electrode OCP [V]"] = LFP_OCP # a customized piecewise function
model = pybamm.lithium_ion.DFN()
param = model.default_parameter_values
timescale = param.esvaluate(model.timescale)
t_end = 0.015*timescale 
t_eval = np.linspace(0, t_end, 1500)
sim = pybamm.Simulation(model, parameter_values=parameter_values)
sim.solve(t_eval = t_eval, initial_soc=0.95) 
```

### Relevant log output

```shell
At t = 0.00500431, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
At t = 4.99029e-06, , mxstep steps taken before reaching tout.
Traceback (most recent call last):
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/solvers/casadi_solver.py", line 669, in _run_integrator
    casadi_sol = integrator(
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/casadi/casadi.py", line 7772, in __call__
    return self.call(kwargs)
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/casadi/casadi.py", line 6945, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/interfaces/sundials/idas_interface.cpp:591: IDASolve returned "IDA_TOO_MUCH_WORK". Consult IDAS documentation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/solvers/casadi_solver.py", line 241, in _integrate
    current_step_sol = self._run_integrator(
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/solvers/casadi_solver.py", line 675, in _run_integrator
    raise pybamm.SolverError(error.args[0])
pybamm.expression_tree.exceptions.SolverError: .../casadi/interfaces/sundials/idas_interface.cpp:591: IDASolve returned "IDA_TOO_MUCH_WORK". Consult IDAS documentation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/archieyao/Desktop/pybamm_run/test.py", line 56, in <module>
    sim.solve(t_eval = t_eval, initial_soc=0.95) # , solver=pybamm.CasadiSolver(mode="safe", dt_max=0.01)
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/simulation.py", line 608, in solve
    self._solution = solver.solve(self.built_model, t_eval, **kwargs)
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/solvers/base_solver.py", line 875, in solve
    new_solution = self._integrate(
  File "/Users/archieyao/tools/miniconda3/lib/python3.9/site-packages/pybamm/solvers/casadi_solver.py", line 276, in _integrate
    raise pybamm.SolverError(
pybamm.expression_tree.exceptions.SolverError: Maximum number of decreased steps occurred at t=226.58912512726562 (final SolverError: '.../casadi/interfaces/sundials/idas_interface.cpp:591: IDASolve returned "IDA_TOO_MUCH_WORK". Consult IDAS documentation.'). For a full solution try reducing dt_max (currently, dt_max=7.08186861061253) and/or reducing the size of the time steps or period of the experiment. Set `return_solution_if_failed_early=True` to return the solution object up to the point where failure occured.
```
```

**Comment by yaomz16** [comment]
I have changed the parameter set according to  https://github.com/pybamm-team/PyBaMM/commit/eabb72040892b964907e01cdc09130a7e25a1489

```
parameter_values = pybamm.ParameterValues("Prada2013")
parameter_values["Current function [A]"] = 1.1 
parameter_values["Typical current [A]"] = 1.1
parameter_values["Initial concentration in negative electrode [mol.m-3]"] = 13584.0
parameter_values["Initial concentration in positive electrode [mol.m-3]"] = 35.0
parameter_values["Positive electrode porosity"] = 0.26
parameter_values["Positive electrode active material volume fraction"] = 0.5846
parameter_values["Positive particle radius [m]"] = 5.00e-8
```

**Comment by yaomz16** [comment]
problem solved, it's because of non-monotonicity of OCV function
