### ISSUE TITLE
Tests fail when scikits not installed

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#310]
**Describe the bug**
All tests fail when scikits not installed, e.g.
```
======================================================================
ERROR: test_discretisations.test_discretisation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_discretisations.test_discretisation
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/ivan/workspace/PyBaMM/tests/unit/test_discretisations/test_discretisation.py", line 4, in <module>
    import pybamm
  File "/home/ivan/workspace/PyBaMM/pybamm/__init__.py", line 174, in <module>
    from .solvers.scikits_dae_solver import ScikitsDaeSolver
  File "/home/ivan/workspace/PyBaMM/pybamm/solvers/scikits_dae_solver.py", line 102, in <module>
    class JacobianFunctionIDA(ida.IDA_JacRhsFunction):
NameError: name 'ida' is not defined
```

**Comment by tinosulzer** [comment]
@martinjrobins  should we have a test setup in travis CRON without scikits installed to catch bugs like this?

**Comment by tinosulzer** [comment]
Imports fixed, now issues with the default solver being `ScikitsOdes` or `ScikitsDaes`. Need to put in an if statement for the default solver.
