### ISSUE TITLE
Fix benchmarks with x-lumped model

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3357]
The benchmarks currently fail when using the x-lumped model with the error message
```bash
/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/base_battery_model.py:886: OptionWarning: The 'lumped' thermal option with 'dimensionality' 0 now uses the parameters 'Cell cooling surface area [m2]', 'Cell volume [m3]' and 'Total heat transfer coefficient [W.m-2.K-1]' to compute the cell cooling term, regardless of the value of the the 'cell geometry' option. Please update your parameters accordingly.
                 options = BatteryModelOptions(extra_options)
               
               For parameters: <class 'pybamm.models.full_battery_models.lithium_ion.spm.SPM'>, 'x-lumped'
               Traceback (most recent call last):
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 1293, in main_run_server
                   main_run(run_args)
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 1167, in main_run
                   result = benchmark.do_run()
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 573, in do_run
                   return self.run(*self._current_params)
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 669, in run
                   samples, number = self.benchmark_timing(timer, min_repeat, max_repeat,
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 705, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/timeit.py", line 177, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/asv/benchmark.py", line 627, in <lambda>
                   func = lambda: self.func(*param)
                 File "/home/runner/work/PyBaMM/PyBaMM/benchmarks/different_model_options.py", line 222, in time_setup_model
                   build_model("Marquis2019", model, "thermal", params)
                 File "/home/runner/work/PyBaMM/PyBaMM/benchmarks/different_model_options.py", line 27, in build_model
                   model = model_({option: value})
                 File "/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/lithium_ion/spm.py", line 43, in __init__
                   super().__init__(options, name)
                 File "/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/lithium_ion/base_lithium_ion_model.py", line 31, in __init__
                   super().__init__(options, name)
                 File "/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/base_battery_model.py", line 800, in __init__
                   self.options = options
                 File "/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/base_battery_model.py", line 886, in options
                   options = BatteryModelOptions(extra_options)
                 File "/home/runner/work/PyBaMM/PyBaMM/env/312c13ab9fc813118206610505b5b72c/lib/python3.8/site-packages/pybamm/models/full_battery_models/base_battery_model.py", line 547, in __init__
                   raise pybamm.OptionError(
               pybamm.expression_tree.exceptions.OptionError: x-lumped model must have pouch cell geometry.
```

**Comment by rtimms** [comment]
In 0D “x-lumped” is equivalent to “lumped” (except the parameters that make up the cooling term are different), so this benchmark option can probably be removed
