### ISSUE TITLE
Error when installing from source in WSL

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3527]
I am trying installing PyBaMM from source using nox in Python 3.11. I am following the instructions in [the docs](https://docs.pybamm.org/en/latest/source/user_guide/installation/install-from-source.html) but it is currently throwing an error (see full log below). Not sure if this is just an issue on my end or a bigger issue:

```bash
nox > Running session pybamm-requires
nox > Re-using existing virtual environment at .nox/pybamm-requires.
nox > python -m pip install wget cmake
Requirement already satisfied: wget in ./.nox/pybamm-requires/lib/python3.11/site-packages (3.2)
Requirement already satisfied: cmake in ./.nox/pybamm-requires/lib/python3.11/site-packages (3.27.7)
nox > python scripts/install_KLU_Sundials.py
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
100% [........................................................................] 64809992 / 64809992---------- Building SuiteSparse_config ----------------------------------------
---------- Building SuiteSparse ----------------------------------------
( cd build && cmake "-DCMAKE_INSTALL_PREFIX=/home/brosaplanella/.local" .. && cmake --build . -j8 )
-- Building SuiteSparse_config version: v6.0.3 (Dec 23, 2022)
-- Source:        /home/brosaplanella/PyBaMM/install_KLU_Sundials/SuiteSparse-6.0.3/SuiteSparse_config 
-- Build:         /home/brosaplanella/PyBaMM/install_KLU_Sundials/SuiteSparse-6.0.3/SuiteSparse_config/build 
-- Install rpath:  
-- Build   rpath: /home/brosaplanella/PyBaMM/install_KLU_Sundials/SuiteSparse-6.0.3/SuiteSparse_config/build 
-- Build type:    Release 
-- Fortran: GNU
-- CUDA: not enabled
-- Detecting Fortran/C Interface
CMake Error: The source "/home/brosaplanella/PyBaMM/.nox/pybamm-requires/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/FortranCInterface/CMakeLists.txt" does not match the source "/home/brosaplanella/PyBaMM/env/lib/python3.9/site-packages/cmake/data/share/cmake-3.25/Modules/FortranCInterface/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
CMake Error at /home/brosaplanella/PyBaMM/.nox/pybamm-requires/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/FortranCInterface/Detect.cmake:49 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  /home/brosaplanella/PyBaMM/.nox/pybamm-requires/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/FortranCInterface.cmake:224 (include)
  cmake_modules/SuiteSparseBLAS.cmake:20 (include)
  CMakeLists.txt:57 (include)


-- Configuring incomplete, errors occurred!
make: *** [Makefile:40: library] Error 1
Traceback (most recent call last):
  File "/home/brosaplanella/PyBaMM/scripts/install_KLU_Sundials.py", line 86, in <module>
    subprocess.run(make_cmd, cwd=build_dir, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', 'library', 'CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/home/brosaplanella/.local"']' returned non-zero exit status 2.
nox > Command python scripts/install_KLU_Sundials.py failed with exit code 1
nox > Session pybamm-requires failed.
```

**Comment by brosaplanella** [comment]
The issues came from some conflicts with previous installations. Cloning the repo again fixed it!
