### ISSUE TITLE
Simplify bug (domains)

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#392]
On the branch `issue-392-simplify-domains-bug`, running
```
python3 tests/unit/test_models/test_lead_acid/test_composite.py
```
raise the following error
```
Traceback (most recent call last):
  File "tests/unit/test_models/test_lead_acid/test_composite.py", line 15, in test_basic_processing
    modeltest.test_all(skip_output_tests=True)
  File "/home/sulzer/Documents/Batteries/PyBaMM/tests/unit/test_models/standard_model_tests.py", line 92, in test_all
    self.test_solving(solver, t_eval)
  File "/home/sulzer/Documents/Batteries/PyBaMM/tests/unit/test_models/standard_model_tests.py", line 77, in test_solving
    self.solver.solve(self.model, t_eval)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/solvers/ode_solver.py", line 35, in solve
    events = [event.simplify() for event in model.events]
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/solvers/ode_solver.py", line 35, in <listcomp>
    events = [event.simplify() for event in model.events]
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/symbol.py", line 477, in simplify
    return pybamm.simplify(self)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/simplify.py", line 548, in simplify
    new_left = simplify(left)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/simplify.py", line 552, in simplify
    new_symbol = symbol._binary_simplify(new_left, new_right)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/binary_operators.py", line 288, in _binary_simplify
    return pybamm.simplify_addition_subtraction(self.__class__, left, right)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/simplify.py", line 178, in simplify_addition_subtraction
    nonconstant_expr = fold_add_subtract(nonconstant, nonconstant_types)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/simplify.py", line 139, in fold_add_subtract
    ret -= child
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/symbol.py", line 236, in __sub__
    return pybamm.Subtraction(self, other)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/binary_operators.py", line 249, in __init__
    super().__init__("-", left, right)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/binary_operators.py", line 78, in __init__
    domain = self.get_children_domains(left.domain, right.domain)
  File "/home/sulzer/Documents/Batteries/PyBaMM/pybamm/expression_tree/binary_operators.py", line 100, in get_children_domains
    ldomain, rdomain
pybamm.expression_tree.exceptions.DomainError: 
                children must have same (or empty) domains, but left.domain is '['positive electrode']'
                and right.domain is '['negative electrode']'
```
and similarly for 
```
python3 tests/unit/test_models/test_lithium_ion/test_lithium_ion_spme.py
```

**Comment by tinosulzer** [comment]
I think I accidentally fixed this in #403 , so closing
